### ISSUE TITLE
视频地址，需要怎么获取

### ISSUE THREAD

**Issue by Sss1986** [techGay/v9porn#10]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 6.0`
- [x] APP 版本：`1.x.x`

#### 自己尝试了哪些，结果如何? ####
现在已经可以运行。 但是视频地址是什么？ 怎么获取

**Comment by chengdr** [comment]
傻狗。建议删帖。。
