### ISSUE TITLE
播放视频显示NullPointerException错误，无法播放

### ISSUE THREAD

**Issue by iKunpw** [techGay/v9porn#100]
### 运行环境 ###

- [x] 手机型号：如：`Samsung Galaxy S9+`
- [x] 系统版本：如 `Android 9.0`
- [x] APP 版本：`1.0.9`

### 具体问题描述(如何操作，有何提示文字等): ###
播放视频显示NullPointerException
#### 问题截图: ####
![1111552882725_ pic](https://user-images.githubusercontent.com/17840850/54506572-0167e500-4978-11e9-8b2e-3f3b8ec78b69.jpg)

**Comment by rotatefish** [comment]
一加5T 安卓9
显示解析视频地址失效了

**Comment by stepbystep2** [comment]
我也这样了🙁

**Comment by Cabchinoe** [comment]
ParseV9PronVideo.java
        final String reg = "document.write\\(atob\\(\"(.*)\"\\)\\);";
        Pattern p = Pattern.compile(reg);
        Matcher m = p.matcher(html);
        String vidsct = "";
        if(m.find()){
            vidsct = m.group(1);
        }
        String source_str = new String(Base64.decode(vidsct.getBytes(),Base64.DEFAULT));
        Document source = Jsoup.parse(source_str);
        String videoUrl = source.select("source").first().attr("src");

//gogogo

**Comment by Z4Xx** [comment]
我也是

**Comment by ILyven** [comment]
求作者大大解决这个问题
