### ISSUE TITLE
Program type already present: io.victoralbertos.jolyglot.JolyglotGenerics

### ISSUE THREAD

**Issue by lxmahtt** [techGay/v9porn#101]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

### 具体问题描述(如何操作，有何提示文字等): ###
AS无法运行：
Program type already present: io.victoralbertos.jolyglot.JolyglotGenerics
请教... 谢谢！

#### 问题截图: ####
![image](https://user-images.githubusercontent.com/38499892/54597214-2429f480-4a71-11e9-8f32-139d66c2e497.png)

#### 自己尝试了哪些，结果如何? ####
https://github.com/techGay/v9porn/issues/94
按照这个方法，修改过版本为0.0.4
但是仍然无法运行
MVPArms版本是2.4.1  依赖的Jolyglot:gson0.0.3

**Comment by techGay** [comment]
MVPArms？？？，你引入这个框架引发的问题，我没办法给你定位

**Comment by techGay** [comment]
试试拉最新版的看看

**Comment by lxmahtt** [comment]
谢谢，找到问题了。就是jar包冲突了。
改了gradle版本好像就会出现这个问题。
删除了jar包就可以了。
