### ISSUE TITLE
目前9*porn 视频已经进行了加密，暂时无法解析视频地址

### ISSUE THREAD

**Issue by techGay** [techGay/v9porn#103]
今天看了一下，目前网站视频地址不再是静态的了
已改为js动态生成，且有一个解密的过程
```
            	  strencode("YisoEFAwLQ0VGHM5B14leHlrMQRXOgNwJ1J2TCQ8KUwXGgxpKl8OTzgYDj1+EkAaURYLOB0oO04GPhVhHhRYRQUDYARbUBtrBRxMFAMsIQhvHiRTK149LTY0MzwiKC0/OyAlYTsADT82bSBrKT4jIQMcagg2Kh4cBhtrfQAkPAgDaTFEPhFlLHwZQRR8IAVN","2cff4hggOK1Cd3hA3YY43rBFk+N4khN9ZpYXf5i6treJ2kyn2RZBQRv9HDLUPWm1fG1+8cJRaKyDQih86dj8f5QeSXbEpDcWZdk8ayWSf9eZgjnVLX+pxnKrOS9Hcci1IZk4dV3Z0+pc","YisoEFAwLQ0VGHM5B14leHlrMQRXOgNwJ1J2TCQ8KUwXGgxpKl8OTzgYDj1+EkAaURYLOB0oO04GPhVhHhRYRQUDYARbUBtrBRxMFAMsIQhvHiRTK149LTY0MzwiKC0/OyAlYTsADT82bSBrKT4jIQMcagg2Kh4cBhtrfQAkPAgDaTFEPhFlLHwZQRR8IAVN")

```
解密方法在md5.js 中，但是js进行了混淆，目前没有时间精力去研究，谁有空解了提交pr吧

**Comment by sygsyg1982** [comment]
https://weibomiaopai.com/online-video-download-helper/91porn

这个地址下把解析服务器改成日本的，能解析出地址

**Comment by techGay** [comment]
靠服务解析获取地址不难，甚至还可以做缓存，之后的请求全部使用缓存，如果无效再去尝试解析，而现在难就难在如何在不运行js脚本的情况下也可以获取，这是最小的代价也是最高效的

最笨最简单的就是开一个webview加载页面，然后等js执行完就可以获取到视频地址了

**Comment by Cabchinoe** [comment]
额, 刚merge就又改了么

**Comment by xiansoyuwe** [comment]
哪个大佬参考一下这个网址更新一下？www.zhaiclub.com

**Comment by Cabchinoe** [comment]
> 哪个大佬参考一下这个网址更新一下？www.zhaiclub.com

fix了,but改了readme  merge的时候忽略吧

**Comment by Cabchinoe** [comment]
> > 哪个大佬参考一下这个网址更新一下？www.zhaiclub.com
> 
> fix了,but改了readme merge的时候忽略吧

https://github.com/techGay/v9porn/pull/105
failed in the first pull however solved this time
