### ISSUE TITLE
1.1版91论坛图片全都无法显示

### ISSUE THREAD

**Issue by 88265189** [techGay/v9porn#107]
1.1版91论坛图片全都无法显示，不知道其他人是否遇到相同情况

**Comment by techGay** [comment]
我这边测试没问题，把你用的地址发我邮箱我试试

**Comment by 88265189** [comment]
重启后可以了。估计我这锤子pro2安装后需要重启，非常感谢！

**Comment by 88265189** [comment]
又有好多天显示不了论坛图片了，重装了重设地址重启，都无法解决问题，还望作者尽快修复。谢谢
