### ISSUE TITLE
无法下载视频！那个加号➕没法点！

### ISSUE THREAD

**Issue by zbb1213440217** [techGay/v9porn#109]
更新了最新版，下载加号的那个视频还是点不了

**Comment by zbb1213440217** [comment]
啥时候能修复一下啊，不能下载好难受

**Comment by techGay** [comment]
你这个我不能复现，不知道具体原因，如何修复，后面考虑在外面列表增加长按选择下载吧

**Comment by zbb1213440217** [comment]
不用修复了，我用了这么久，才知道原来手机的实体键可以呼出下载啊还有评论界面的，不用点加号了！

**Comment by techGay** [comment]
想来是实体键的手机默认走了什么东西了导致不可点击，我也是醉了
