### ISSUE TITLE
论坛图片不可见

### ISSUE THREAD

**Issue by chaosmol** [techGay/v9porn#11]
### 运行环境 ###

- [x] 手机型号：如：`huawei mate8`
- [x] 系统版本：如 `Android 7.0`
- [x] APP 版本：`1.x.x`

#### 自己尝试了哪些，结果如何? ####
编译完成，过程中有提示WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
运行的时候，论坛里的图片都是看不到的。前一个版本可以看得到。

**Comment by techGay** [comment]
这个错误没有关系。这个问题也说过了，因为最新地址已经变了，虽然你原地址也可以访问（服务器那边帮你自动跳转了），但是图片链接是基于你本地的地址拼接生成的，所以自然就无法显示了。

目前解决办法：使用最新地址即可，后面在改进了

**Comment by chaosmol** [comment]
哦哦，好的。感谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: liang <notifications@github.com>
发送时间: Friday, April 20, 2018 8:58:22 PM
收件人: techGay/v9porn
抄送: chaosmol; Author
主题: Re: [techGay/v9porn] 论坛图片不可见 (#11)


这个错误没有关系。这个问题也说过了，因为最新地址已经变了，虽然你原地址也可以访问（服务器那边帮你自动跳转了），但是图片链接是基于你本地的地址拼接生成的，所以自然就无法显示了。

目前解决办法：使用最新地址即可，后面在改进了

―
