### ISSUE TITLE
哪位大佬能解答一下解析思路

### ISSUE THREAD

**Issue by asingers1** [techGay/v9porn#110]
M3sqQDcAJyFrNQUcMUIbCgdiK0dVJTh/HUF6QBwoGxQJHgFMfWUkQwoEOzsYQVoCM3YLHXkKIhwBDipOGC9RLVQxemgpR2ddfGMsZRUlOXYHLQQ8fjJZNxl+T2IMWhVLHQBrWiNjblQ+BHF2dgweZww2KC43IxkiIH4WWxsLL00fXCM5Kz8zRXhxUDItcAcd","c3d6SXmK1fGfR/V3MPCw1myIQ8B8SlNaDdf901i6GPvLT8cvP2Zg5pokNJc9WldY7u+GJt6d1RHQCbw3Tj5M+Y1qzLv7VkD3I2R4r048nP4G8XSWAryYxgTLi6DnxLztUoyIqxe34CaE","M3sqQDcAJyFrNQUcMUIbCgdiK0dVJTh/HUF6QBwoGxQJHgFMfWUkQwoEOzsYQVoCM3YLHXkKIhwBDipOGC9RLVQxemgpR2ddfGMsZRUlOXYHLQQ8fjJZNxl+T2IMWhVLHQBrWiNjblQ+BHF2dgweZww2KC43IxkiIH4WWxsLL00fXCM5Kz8zRXhxUDItcAcd

这串加密的东西怎么解？

**Comment by longwusha** [comment]
数据来源是？哪个接口拿到的，哪个接口要用？稍微提供点关联信息啊，如果这样子什么都没有，谁都没辙，只能硬猜，各种加密算法去试了
