### ISSUE TITLE
“+”号的功能去丢失了吗

### ISSUE THREAD

**Issue by lonadong** [techGay/v9porn#111]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

在视频列表状态下，那个“+”号功能正常，但在任一一个视频的播放页面中，“+”不工作了，也就不能下载了。谢谢啦！

**Comment by techGay** [comment]
机型，系统版本也没说，这种诡异的bug本就不好复现，现在没有任何信息，如何判断？

**Comment by lonadong** [comment]
你好，真的感谢你的回复，这是平板的信息：
Lenovo TAB 2 A7-20F,Android 4.4.2,V9porn:v1.1.0.

不熟息安卓系统，可不可以告我一下app 的安装路径，是不是原来的程序没有删除干净呢？确实是在每一个视频的列表状态下，“+”功能正常，进入视频播放页面后，“+”就不用了，没反应了！有时候网友的回复条也会覆 盖住“+”，时有时无的。

谢谢🙏！



Sent from my iPhone

On 25 Mar 2019, at 12:21 AM, Liang <notifications@github.com<mailto:notifications@github.com>> wrote:


机型，系统版本也没说，这种诡异的bug本就不好复现，现在没有任何信息，如何判断？

**Comment by techGay** [comment]
这跟原来的程序没关系，你这是平板，本来就没适配，应该是有地方计算错误了

**Comment by lonadong** [comment]
好的，只能这样了。正常的情况应该是按一下加号，下面弹出来一个选择条，再选择其中的功能，现在是完全没有反应，能告我一下安装的目录么？谢谢你！

Sent from my iPhone

On 26 Mar 2019, at 9:57 AM, Liang <notifications@github.com<mailto:notifications@github.com>> wrote:


这跟原来的程序没关系，你这是平板，本来就没适配，应该是有地方计算错误了
