### ISSUE TITLE
91解析视频时，大概率会无限loading

### ISSUE THREAD

**Issue by geekvxyz** [techGay/v9porn#112]
### 运行环境 ###

- [x] 手机型号：`小米Max 2`
- [x] 系统版本：`PeixlE Android 9`
- [x] APP 版本：`1.1.0`

### 具体问题描述(如何操作，有何提示文字等): ###
加载视频无限loading，可进入详情页

**Comment by techGay** [comment]
应该你自己的网络环境问题，我本地测试没有发现
