### ISSUE TITLE
貌似今天彻底失效了，三个网站没一个可以了！哎

### ISSUE THREAD

**Issue by daialing** [techGay/v9porn#113]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by llh1187** [comment]
是哪三个网站呢？

**Comment by llh1187** [comment]
不怕你笑我 我只知道一个91porn 还有别的是什么呢？
