### ISSUE TITLE
登录功能无法使用

### ISSUE THREAD

**Issue by timoduizhang** [techGay/v9porn#114]
### 运行环境 ###

- [x] 手机型号：如：`xiaomi note3`
- [x] 系统版本：如 `Android 8.1`
- [x] APP 版本：`1.1.0`

### 具体问题描述(如何操作，有何提示文字等): ###
官网新注册的账号，可以在官网登录。
打开app进入到登录页面，输入账号密码验证码，点击登录，会出现登录中的loading。过了大概3秒，该loading消失，仍旧停在登录页面。尝试几次都是这种结果。望大佬解决

**Comment by techGay** [comment]
我本地测试旧帐号是可以登录的，目前存在的问题就是登录之后会显示不出用户名

目前不太确定是不是跟新帐号有关系，回头我看看

**Comment by timoduizhang** [comment]
@techGay  感谢大佬回复，我是拿新账号尝试登录，无论输入正确密码还是错误密码都是以上的情况，没有密码错误的提示。

**Comment by dutry** [comment]
@techGay 

小米max3 
android 9 （miui 10.2）
app版本1.1

出现的不能登陆的情况和楼主一模一样，无法登陆。
