### ISSUE TITLE
建议把搜索功能加上

### ISSUE THREAD

**Issue by kiritojoker** [techGay/v9porn#115]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by techGay** [comment]
把建议说详细点，说这么模糊没得理解

你还需要哪些搜索功能？

**Comment by neverbeshy** [comment]
91搜索功能

**Comment by zzzop** [comment]
> 91搜索功能

有搜索的。。

**Comment by neverbeshy** [comment]
每个地址设置能发下吗？一直不太会用

zzzop <notifications@github.com> 于2019年5月26日周日 上午10:05写道：
