### ISSUE TITLE
建议拉一个future列表，想帮忙不知道改什么好

### ISSUE THREAD

**Issue by wanghws** [techGay/v9porn#116]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [ ] 系统版本：如 `Android 5.0`
- [ ] APP 版本：`1.x.x`

**Comment by techGay** [comment]
你有什么好的想法都可以改呀。
issues里的问题，你要是知道可以改了提交，还有我代码很多地方都写的不好，你也可以改了提交
