### ISSUE TITLE
91论坛图片无法加载

### ISSUE THREAD

**Issue by windghoul** [techGay/v9porn#118]
### 运行环境 ###

- [x] 手机型号：如：`三星s7edge`
- [x] 系统版本：如 `Android 8.0`
- [x] APP 版本：`1.1.0`

### 具体问题描述(如何操作，有何提示文字等): ###
文字显示正常，图片无法加载。
图片无法加载情况为，前方出现碎图[图片无法加载...]

#### 自己尝试了哪些，结果如何? ####
在同网络环境下，用浏览器测试图片加载正常

**Comment by windghoul** [comment]
提个改进，图片论坛地址可以在主页的 xpath ：//*[@id="navcontainer"]/ul/li[4]/a/@href 下读取数据，这样就不用设置图片论坛的地址了

**Comment by techGay** [comment]
你可以直接提交pr，我合并就可以了

**Comment by windghoul** [comment]
> 你可以直接提交pr，我合并就可以了

我不懂安卓，不过可以尝试一下

**Comment by twosmallhands** [comment]
同无法加载图片
