### ISSUE TITLE
avgle视频显示的封面和打开的视频内容不符 

### ISSUE THREAD

**Issue by tap123123** [techGay/v9porn#120]
### 运行环境 ###

- 手机型号:`华为mt7`
- 系统版本:`Android 6.0`
- APP 版本:`1.1.0`

avgle视频显示的封面和打开的视频内容不符

**Comment by techGay** [comment]
Duplicate of #87

**Comment by flycatzlz** [comment]
我也有这个问题，视频播放地址和实际不符合

**Comment by carsonmoon** [comment]
为啥我连avgle视频都加载不进去 能看到图片和预览图 点进去就是黑屏 一直等也不加载
