### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by GFY007** [techGay/v9porn#127]
### 运行环境 ###

- [x] 手机型号：xiaomi redmi note7
- [x] 系统版本：Android 9.0
- [x] APP 版本：1.1.2
具体问题描述:登陆的时候一直加载，然后过几秒钟加载没了，但是还在登陆的页面，退出去也没有登陆成功，等了一会儿还是没变化

**Comment by GFY007** [comment]
主页视频左边的预览图也加载不出来

**Comment by techGay** [comment]
1.  登录问题有空再看了
2.  加载不出来是你自己的网络问题
