### ISSUE TITLE
突破视频观看数量限制的原理？

### ISSUE THREAD

**Issue by BCsl** [techGay/v9porn#13]
如题，原理是对 `X-Forwarded-For` 这个 `header` 构造随机的 ip ？

**Comment by techGay** [comment]
就是，懂X-Forwarded-For这个请求头就差不多了，因为服务器是基于ip+本地cookie记录判断的，所以你浏览器清除cookie没有用，只有让服务器认为你是不同ip也就是不同用户即可，除非以后服务器基于用户账号限制，不然还可以通过HTTP代理突破，更深的了解你需要懂IP等等相关的内容

**Comment by DLTech21** [comment]
@techGay 具体代码在哪个类？我现在用iOS仿写一个，遇到如何突破ip
