### ISSUE TITLE
登录错误问题我找到了

### ISSUE THREAD

**Issue by marud1024** [techGay/v9porn#130]
com.u9porn.parser.ParseV9PronVideo 
326行
String lastLoginTime = userContent.substring(userContent.indexOf("最后登录"), userContent.indexOf("IP:"));
        //String lastLoginIP = userContent.substring(userContent.indexOf("IP:"), userContent.indexOf("点此查看"));
        user.setLastLoginTime(lastLoginTime);
        user.setLastLoginIP("");

        Logger.t(TAG).d(lastLoginTime);
        //Logger.t(TAG).d(lastLoginIP);

**Comment by techGay** [comment]
你可以提交PR，如果不是视频看不了，其他的问题近期我可能没有太多的时间来改
