### ISSUE TITLE
有没有办法，一次下载最近一年的，或者批量下载

### ISSUE THREAD

**Issue by usbcdrom** [techGay/v9porn#133]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by zpswz** [comment]
你是想牟利吧？

**Comment by JammyR** [comment]
为了你的身体健康考虑，暂不提供此功能

**Comment by usbcdrom** [comment]
> 为了你的身体健康考虑，暂不提供此功能

身体太好了，夏天走在城市中看着美腿看着坦胸露乳的母的，为了不犯罪，决定下载很多在家里把我自费了，撸到灰飞烟灭

**Comment by 3243935180** [comment]
我是为了修改成正规视频软件，

**Comment by 3243935180** [comment]
😂

**Comment by jenosn** [comment]
> 为了你的身体健康考虑，暂不提供此功能
这个现在还能用吗

**Comment by usbcdrom** [comment]
没事我身体很好，临时提供下功能也可以，有偿，谢谢大佬


 
---原始邮件---
发件人: "jenosn"<notifications@github.com>
发送时间: 2019年7月8日(星期一) 晚上6:07
收件人: "techGay/v9porn"<v9porn@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"usbcdrom"<87798856@qq.com>;
主题: Re: [techGay/v9porn] 有没有办法，一次下载最近一年的，或者批量下载 (#133)


 
为了你的身体健康考虑，暂不提供此功能
 这个现在还能用吗
