### ISSUE TITLE
求定制这个项目有偿

### ISSUE THREAD

**Issue by 3243935180** [techGay/v9porn#135]
修改底部导航为加载百度提供源码和apk。能帮我修改的话加我付款或者提供网盘下载链接也行赞赏码付款也可以！有偿66元支付宝h200279@163.com联系方式QQ：3243935180加QQ或者支付宝。

**Comment by drduan** [comment]
啥意思

**Comment by 3243935180** [comment]
有偿，将这个改成hybridh5的视频软件，用来做短视频
