### ISSUE TITLE
点击具体视频解析地址失败

### ISSUE THREAD

**Issue by jenosn** [techGay/v9porn#136]
### 运行环境 ###

- [x] 手机型号：如：`一加3T`
- [x] 系统版本：如 `Android 9.0`
- [x] APP 版本：`最新版本`

### 具体问题描述(如何操作，有何提示文字等): ###
点击具体视频解析地址失败

**Comment by MorningStarHu** [comment]
哥 能讲一下怎么用吗

**Comment by feng1632009** [comment]
这个91的视频地址和论坛地址有什么不一样么 你是设置的一样么？ 虽然能看到视频页，但点进去视频无法解析，你是这样么？

**Comment by luodp9** [comment]
∪･ω･∪
