### ISSUE TITLE
没地址有毛用

### ISSUE THREAD

**Issue by 599070001** [techGay/v9porn#137]
垃圾开源，没地址有毛的用

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by IPlayForHer** [comment]
不如你做一个，然后把地址也写进去，然后你就进去了

**Comment by IPlayForHer** [comment]
还有都知道上GitHub了还能找不到地址您怕不是个弟弟
