### ISSUE TITLE
啊啊啊, 老哥怎么关了啊啊

### ISSUE THREAD

**Issue by RJJxp** [techGay/v9porn#140]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by wishfulJ** [comment]
问题138

**Comment by usbcdrom** [comment]
不知道啊，这么好的项目就给停止跟新了

**Comment by usbcdrom** [comment]
怎么就关了
