### ISSUE TITLE
关于升级的问题…

### ISSUE THREAD

**Issue by cnjn** [techGay/v9porn#145]
呐…作者大人宣布停止维护项目了…咱也没办法……也不能昧着良心再要求啥…可我看到了1.0.9升级至1.1.2的提示，偏生我的手机又是安卓9，所以无法自动下载…更新提示里边儿说可以手动下载，可是…我真的没找到手动下载的地址啊…😥作者大人能不能行行好，让我这个强迫症患者顺利升级了？(可以在升级提示中附上手动下载地址吗？)跪求啊😜

**Comment by techGay** [comment]
你懂自然还能找到，不懂就自己下载源码编译安装。
