### ISSUE TITLE
X86 android install failed

### ISSUE THREAD

**Issue by QiuMike** [techGay/v9porn#152]
10-25 05:28:03.458   797   797 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
10-25 05:28:03.465   797   797 D AndroidRuntime: CheckJNI is OFF
10-25 05:28:03.465   797   797 E cutils-trace: Error opening trace file: No such file or directory (2)
10-25 05:28:03.570   797   797 W art     : Unexpected CPU variant for X86 using defaults: x86_64
10-25 05:28:03.585   797   797 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
10-25 05:28:03.621   797   797 E memtrack: Couldn't load memtrack module (No such file or directory)
10-25 05:28:03.621   797   797 E android.os.Debug: failed to load memtrack module: -2
10-25 05:28:03.623   797   797 I Radio-JNI: register_android_hardware_Radio DONE
10-25 05:28:03.647   797   797 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
10-25 05:28:03.670    34    34 I         : free_cache(65330) avail 5932470272
10-25 05:28:03.691   111   138 D         : Zip: EOCD not found, /data/app/vmdl1288050713.tmp/base.apk is not zip
10-25 05:28:03.691   111   138 W zipro   : Error opening archive /data/app/vmdl1288050713.tmp/base.apk: Invalid file
10-25 05:28:03.691   111   138 D asset   : failed to open Zip archive '/data/app/vmdl1288050713.tmp/base.apk'
10-25 05:28:03.696   111   138 E PackageInstaller: Commit of session 1288050713 failed: Failed to parse /data/app/vmdl1288050713.tmp/base.apk: AndroidManifest.xml
10-25 05:28:03.707    34    34 E         : Couldn't opendir /data/app/vmdl1288050713.tmp: No such file or directory
10-25 05:28:03.715   797   797 I art     : System.exit called, status: 1
10-25 05:28:03.715   797   797 I AndroidRuntime: VM exiting with result code 1.

**Comment by techGay** [comment]
看起来像是系统安装 apk时无法正确解析安装包，单从目前的日志看不出原因以及其他的问题

请问使用的是什么机型？系统android版本？是自己构建的apk还是使用上传的apk？

**Comment by iknow4** [comment]
@QiuMike 
这是安装失败的错误，应该是你本地的项目中没有配置支持x86_64 的cpu架构。
