### ISSUE TITLE
91视频地址添加不了，提示503

### ISSUE THREAD

**Issue by Butcherr** [techGay/v9porn#153]
91视频地址添加不了，提示503。其他正常

**Comment by saivin** [comment]
一样，503了

**Comment by techGay** [comment]
503 是服务器的问题，跟客户端没关系

**Comment by wyk19950704** [comment]
403

**Comment by Butcherr** [comment]
> 503是服务器的问题，跟客户端没关系

403是什么问题

**Comment by techGay** [comment]
403 是服务器拒绝访问，目前应该是服务器用了google的机器人验证api了

**Comment by Butcherr** [comment]
> 403是服务器拒绝访问，目前看来应该是服务器用了Google的机器人验证api了

可以用了，谢谢修复

**Comment by MingHaoDu** [comment]
> > 403是服务器拒绝访问，目前看来应该是服务器用了Google的机器人验证api了
> 
> 可以用了，谢谢修复

请问用啥地址啊？

**Comment by JlyNeo** [comment]
> > 403是服务器拒绝访问，目前看来应该是服务器用了Google的机器人验证api了
> 
> 可以用了，谢谢修复

现在还能用嘛，又出现了

**Comment by JlyNeo** [comment]
> 403是服务器拒绝访问，目前看来应该是服务器用了Google的机器人验证api了

404是什么问题啊，大佬
