### ISSUE TITLE
编译生成问题请教

### ISSUE THREAD

**Issue by windy1lee** [techGay/v9porn#16]
1、项目导入时出现错误：
org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'http://jcenter.bintray.com/com/bugsnag/bugsnag-android-gradle-plugin/maven-metadata.xml'.
挂梯子也没有搞定。打开这个网址404.
2、为什么我的AS菜单build下面没有Generate Signed APK这个选项，只有build apk这个。

**Comment by wjm2038** [comment]
@windy1lee 并不是404,文件是这个.
[maven-metadata.xml.txt](https://github.com/techGay/v9porn/files/1944294/maven-metadata.xml.txt)

**Comment by windy1lee** [comment]
这个文件放在哪里的？？

**Comment by wjm2038** [comment]
我留在评论里啊,你用电脑就能看到,我指的是那个连接不是404
