### ISSUE TITLE
兄弟们更新了，现在能用吗

### ISSUE THREAD

**Issue by usbcdrom** [techGay/v9porn#168]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by xuzhike123** [comment]
红米note5
Android 9.0
APP版本1.1.4
![image](https://user-images.githubusercontent.com/46637868/71397093-737fff80-2657-11ea-8942-b9a36fb4f528.png)

**Comment by neimengwuyanzu** [comment]
这个看介绍是因为用了永久地址  用代理地址就好了

**Comment by JlyNeo** [comment]
> 这个看介绍是因为用了永久地址 用代理地址就好了

老哥能给个私信方式嘛

**Comment by neimengwuyanzu** [comment]
> > 这个看介绍是因为用了永久地址 用代理地址就好了
> 
> 老哥能给个私信方式嘛

我也没有 开发者也不让分享

**Comment by JlyNeo** [comment]
> > > 这个看介绍是因为用了永久地址 用代理地址就好了
> > 
> > 
> > 老哥能给个私信方式嘛
> 
> 我也没有 开发者也不让分享

不是分享，想问下遇到的问题

**Comment by techGay** [comment]
验证通过就能用
