### ISSUE TITLE
能看了，但是还是不能登录

### ISSUE THREAD

**Issue by ldp00914** [techGay/v9porn#170]

**Comment by JlyNeo** [comment]
楼主能给个私信方式吗，询问一个问题。。。

**Comment by usbcdrom** [comment]
这个验证真是不好搞了

**Comment by JlyNeo** [comment]
> 这个验证真是不好搞了

验证上去了却啥也不显示

**Comment by luodp9** [comment]
@JlyNeo qq945110116

**Comment by techGay** [comment]
不能登录可能是帐号存在问题，有的帐号登录会提示改密码，先去官网改好密码在登录，如果还是不能登录，等我有时间再看看什么问题

**Comment by superwqc** [comment]
老铁能给个联系方式吗？

**Comment by nh560** [comment]
> _No description provided._

老铁，能加个Q吗1097885640
