### ISSUE TITLE
Google验证过去了以后什么都不显示

### ISSUE THREAD

**Issue by JlyNeo** [techGay/v9porn#172]
### 运行环境 ###
手机型号：如：小米8
系统版本：Android 9
APP 版本：1.1.4

#### 问题截图: 
![Screenshot_2019-12-26-16-07-46-755_com u9porn](https://user-images.githubusercontent.com/45449398/71477554-9bbd5900-2825-11ea-9304-f9093b46de14.jpg)
就变成这样，没有反应，重新测试还是原来的样子

**Comment by JlyNeo** [comment]
![绘图1](https://user-images.githubusercontent.com/45449398/71477477-500aaf80-2825-11ea-88bc-3f1faf7ea389.jpg)

**Comment by techGay** [comment]
这个界面不会显示多余的信息，提示验证成功，界面自动关闭就代表验证成功，已经获取到访问需要的cookie信息，直接去主页面刷新重新加载即可。

**Comment by JlyNeo** [comment]
> 这个界面不会显示多余的信息，提示验证成功，界面自动关闭就代表验证成功，已经获取到访问需要的cookie信息，直接去主页面刷新重新加载即可。

但是界面没有自动关闭，一直停留在这里，退出去之后再进来还需要验证

**Comment by JlyNeo** [comment]
> 这个界面不会显示多余的信息，提示验证成功，界面自动关闭就代表验证成功，已经获取到访问需要的cookie信息，直接去主页面刷新重新加载即可。

没有登陆账号，就是出现了google验证完成后不会自动退出，一直停留在这个界面

**Comment by techGay** [comment]
你的验证页面是怎么样的，验证完成之后有什么提示

**Comment by JlyNeo** [comment]
> 你的验证页面是怎么样的，验证完成之后有什么提示

![Screenshot_2019-12-26-21-51-53-284_com u9porn](https://user-images.githubusercontent.com/45449398/71478334-ffe21c00-2829-11ea-9b48-accbabb8e725.jpg)
验证界面就是这样，在完成界面验证后会出现下方全部变成空白，不会自动退出，我的机型是小米8
安卓版本9

**Comment by techGay** [comment]
那可能跟你的机型和系统版本有关吧，文字提示呢，显示的什么文字提示

**Comment by JlyNeo** [comment]
> 那可能跟你的机型和系统版本有关吧，文字提示呢，显示的什么文字提示

没有任何文字提示，就是空白，退出再进去验证还是一样

**Comment by techGay** [comment]
那我回头用模拟器测测android9吧，如果可以那就是小米机型问题，做了特定的拦截之类的吧

**Comment by JlyNeo** [comment]
> 那我回头用模拟器测测android9吧，如果可以那就是小米机型问题，做了特定的拦截之类的吧

好的，谢谢大佬

**Comment by usbcdrom** [comment]
91这个垃圾网站草

**Comment by lkxed** [comment]
红米Note7Pro Android 9 MIUI 11 遇到了同样的问题

**Comment by saivin** [comment]
之前在http后面加了一个s一直出错，去掉s就可以访问了

**Comment by JlyNeo** [comment]
> 之前在http后面加了一个s一直出错，去掉s就可以访问了

经过验证，确实是这个问题，应该和手机型号没关系

**Comment by techGay** [comment]
我测试了，模拟器没有问题，那就是你们自己地址设置没对

**Comment by JlyNeo** [comment]
> 我测试了，模拟器没有问题，那就是你们自己地址设置没对

是的，重新设置了地址可以了，辛苦大佬了
