### ISSUE TITLE
问题反馈：地址解析错误

### ISSUE THREAD

**Issue by ztcc** [techGay/v9porn#177]
### 运行环境 ###

- [x] 手机型号：小米5
- [x] 系统版本：Android 8 MIUI 10.2
- [x] APP 版本：1.1.3   1.1.4

1.首页刷新能加载，点击视频后显示地址加载失败；
2.尝试更换最新地址、更新最新版本客户端，无效；
3.使用科学上网，无效。

**Comment by ceculean** [comment]
同样的问题
