### ISSUE TITLE
图片是不是挂了

### ISSUE THREAD

**Issue by mjnhmd** [techGay/v9porn#18]
java.io.IOException: unexpected end of stream on Connection{www.mzitu.com:80, proxy=DIRECT hostAddress=www.mzitu.com/113.13.17.71:80 cipherSuite=none protocol=http/1.1}

**Comment by techGay** [comment]
没挂的，你开代理导致乱了，目前似乎开代理就算设置了规则可能也会这样，具体原因还不清楚

**Comment by mjnhmd** [comment]
哦 是了。。。我连的是wifi，这个wifi把这个这个网址屏蔽了
