### ISSUE TITLE
AppApiHelperl中loadPorn9VideoUrl导致析视频地址失败

### ISSUE THREAD

**Issue by WalkingBoys** [techGay/v9porn#180]
### 具体问题描述(如何操作，有何提示文字等): ###
 public Observable<VideoResult> loadPorn9VideoUrl(String viewKey) {
        String ip = addressHelper.getRandomIPAddress();
        //因为登录后不在返回用户uid，需要在此页面获取，所以当前页面不在缓存，确保用户登录后刷新当前页面可以获取到用户uid
        return v9PornServiceApi.getVideoPlayPage(viewKey, ip, HeaderUtils.getIndexHeader(addressHelper))
                .map(html -> videoPlayUrlParser.parseVideoPlayUrl(html,user));
    }
#### 自己尝试了哪些，结果如何? ####
  这个.map内函数不会执行，重写map编译后才可以正常拿到videoresult，播放视频

**Comment by techGay** [comment]
会执行的
