### ISSUE TITLE
V1.1.5 出現未安裝應用程式，無法安裝

### ISSUE THREAD

**Issue by gto3031** [techGay/v9porn#183]
### 运行环境 ###

- [x] 手机型号：如：`Samsung S9PLUS`
- [x] 系统版本：如 `Android 9.0 10.0`
- [x] APP 版本：`1.1.5`

### 具体问题描述(如何操作，有何提示文字等): ###
移除1.1.4版本後安裝與透過1.1.4版本安裝均出現
未安裝應用程式，不能安裝1.1.5版本
#### 自己尝试了哪些，结果如何? ####
從安卓9.0更新到10.0都無法
舊資料夾也移除了還是安裝不了

**Comment by rudyxp** [comment]
卸载旧的app再安装就好了

**Comment by gto3031** [comment]
卸載後安裝一樣不行，不能用神器看，好難過

**Comment by gto3031** [comment]
找到原因了，原來我有放在三星的安全資料夾內，把裡面的卸載後可安裝了，謝謝大神

**Comment by nh560** [comment]
老铁们能私下交流一下吗

**Comment by nh560** [comment]
老铁能加个联系方式吗
