### ISSUE TITLE
提问：兼容 iOS系统的软件是否有意向开发？ 

### ISSUE THREAD

**Issue by tank12395** [techGay/v9porn#185]
### 运行环境 ###

- [x] 手机型号：如：iPhone 11
- [x] 系统版本：如：iOS 13.3.1

之前一直安卓平台使用，最近换iPhone了导致一直无法使用，
希望开发者可以考虑下开发iOS系统的软件或者其他替代品能在iOS系统上使用。

**Comment by techGay** [comment]
暂时没有这个打算

**Comment by shangleixun** [comment]
> 暂时没有这个打算

使用者提要求就是一张嘴，作者免费做这个应用，除了对人间全是爱，别无所求了。iOS 注册能发布应用的开发者还要钱，苹果也不允许色情内容出现在 App Store 中的应用里，大家对 iOS 版就别多想了。
