### ISSUE TITLE
新版的下载视频不能在APP里播放，还有zgl不能播放，之前的老版1.1.5没这问题

### ISSUE THREAD

**Issue by mazheng127** [techGay/v9porn#19]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by mazheng127** [comment]
新版的下载视频不能在APP里播放，还有zgl不能播放，之前的老版1.1.5没这问题

**Comment by techGay** [comment]
1，下载视频不能播放原因已找到

2，zgl在线可以播放，没有问题

**Comment by mazheng127** [comment]
我这zgl不能播放，1.1.5版本点进去就开始播放了，还有打开软件新版会黑屏一会才会显示内容，1.1.5是点进去立即内容就显示出来了
