### ISSUE TITLE
不能登陆：未知错误，请确认地址是否正确

### ISSUE THREAD

**Issue by kobepejanash** [techGay/v9porn#2]
### 运行环境 ###

- [ ] 手机型号：如：`Nexus 6`
- [ ] 系统版本：如 `Android 5.0`
- [ ] APP 版本：`1.x.x`

**Comment by kobepejanash** [comment]
还多了一个叫leak的软件

**Comment by techGay** [comment]
你没有打release包自然有这个软件，错误的话多换几个地址试吧，目前似乎有些地址会这样

**Comment by kobepejanash** [comment]
已经解决，感谢作者
