### ISSUE TITLE
问题 & 建议

### ISSUE THREAD

**Issue by northyzq** [techGay/v9porn#20]
### 运行环境 ###

- [x] 手机型号：如：`坚果pro2`
- [x] 系统版本：如 `Android 7.1.1`
- [x] APP 版本：`1.0.0`

### 具体问题描述(如何操作，有何提示文字等): ###

问题:
1, 坚果pro2运行软件, 存在不全屏问题, 白色底边
备注: (坚果pro2设置为全屏模式, 无系统导航栏, 通过滑动实现返回,主菜单等功能)

建议:
1, 可否考虑实现个手机投屏功能, 类似腾讯视频投屏这种

#### 问题截图: ####

![image](https://user-images.githubusercontent.com/10533623/39346602-981b598e-4a21-11e8-8034-a876450881e0.png)

#### 自己尝试了哪些，结果如何? ####

None

**Comment by techGay** [comment]
1，已经在配置文件中声明了全面屏适配，去官网逛了一圈没看到适配sdk文档之类的，暂时不知道还有其他的办法适配
2.我稍微查了，android关于dlna的资料不多，目前暂时不会考虑
