### ISSUE TITLE
想请教下作者，是如何绕过年龄确认页面的？

### ISSUE THREAD

**Issue by sth0409** [techGay/v9porn#200]
想在作者的基础上改一个TV版的自用，奈何dragger2绑定关系太多，看源码看的云里雾里的。
现在通过***已经200了但是却是年龄确认页面。
想问下作者是通过什么手段绕过的？

**Comment by sth0409** [comment]
dagger

**Comment by techGay** [comment]
直接加载index.php界面，还有请求头header设置，我没有碰到过这个问题，具体分析还得看你的代码怎么写的

这个和dagger2没啥关系，dagger2只是依赖注入而已

**Comment by sth0409** [comment]
> 直接加载index.php界面，还有请求头header设置，我没有碰到过这个问题，具体分析还得看你的代码怎么写的
> 
> 这个和dagger2没啥关系，dagger2只是依赖注入而已



> 直接加载index.php界面，还有请求头header设置，我没有碰到过这个问题，具体分析还得看你的代码怎么写的
> 
> 这个和dagger2没啥关系，dagger2只是依赖注入而已

**Comment by sth0409** [comment]
> 直接加载index.php界面，还有请求头header设置，我没有碰到过这个问题，具体分析还得看你的代码怎么写的
> 
> 这个和dagger2没啥关系，dagger2只是依赖注入而已

嗯嗯 好的 我再试一下 我是直接用另外一个请求框架加请求头来弄的 
哈哈  的确和dagger2没关系  只是因为drager2 作者的部分方法没法通过new来直接调用
很少提issue 竟然手滑关闭了
