### ISSUE TITLE
zgl点开播放显示播放地址无效，1.1.5版本可以正常播放，什么原因

### ISSUE THREAD

**Issue by mazheng127** [techGay/v9porn#22]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by mazheng127** [comment]
ZGL点开播放显示播放地址无效，1.1.5版本可以正常播放，什么原因

**Comment by techGay** [comment]
别重复开相同的issue，地址正确，有梯子就能正常播放，没有问题，不行就卸载重新安装，重新设置地址

**Comment by mazheng127** [comment]
重新打包安装还是一样，同样的地址在1.1.5就可以

**Comment by techGay** [comment]
播放地址无效就是解析不到视频的地址，你可以自己断点播放界面解析视频地址那里看看数据是什么样的

**Comment by mayunbaba2** [comment]
地址是什么 求

**Comment by techGay** [comment]
ok

**Comment by bluechan** [comment]
请问ZGL地址多少，谢谢

**Comment by bluechan** [comment]
@mazheng127 请问ZGL地址多少，谢谢
