### ISSUE TITLE
获取播放地址的view_video.php接口用不了？？

### ISSUE THREAD

**Issue by xiaoOops** [techGay/v9porn#220]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

#### 自己尝试了哪些，结果如何? ####

debug了下源码，发现了这个接口返回的html是空的，是哪里的问题？

/**
     * 访问页面获取视频地址页面
     * 
     *
     * @param viewkey   视频的key
     * @return body
     */
    @Headers({"Domain-Name: " + Api.PORN9_VIDEO_DOMAIN_NAME})
    @GET("/view_video.php")
    Observable<String> getVideoPlayPage(@Query("viewkey") String viewkey, @Header("Referer") String referer);

**Comment by techGay** [comment]
没理由获取不到吧，你可以复制实际的地址到电脑浏览器看看

**Comment by xiaoOops** [comment]
> 没理由获取不到吧，你可以复制实际的地址到电脑浏览器看看

实际地址用浏览器可以渲染打开。代码里这个接口返回的就是空的，parseVideoPlayUrl时会抛空指针出来。

**Comment by xiaoOops** [comment]
刚刚又试了下，有时候可以拿到，有时候拿不到，怀疑是我梯子的问题。。。

**Comment by techGay** [comment]
> 刚刚又试了下，有时候可以拿到，有时候拿不到，怀疑是我梯子的问题。。。

也有可能是服务器抽风

**Comment by xiaoOops** [comment]
> > 刚刚又试了下，有时候可以拿到，有时候拿不到，怀疑是我梯子的问题。。。
> 
> 也有可能是服务器抽风

我复现了，刚进来加载的第一页没问题。具体操作是：进入app，先在当前页点一个视频，接口没问题，退出返回列表往下翻页之后，再点进去加载视频，这个接口返回的html就是空的了。

**Comment by techGay** [comment]
> > > 刚刚又试了下，有时候可以拿到，有时候拿不到，怀疑是我梯子的问题。。。
> > 
> > 
> > 也有可能是服务器抽风
> 
> 我复现了，刚进来加载的第一页没问题。具体操作是：进入app，先不要点第一个tab的视频，多往右划几个tab，然后往下多翻几页，点进去大概率会造成这个接口返回为空。。。

那可能是他们有搞了什么鬼了
