### ISSUE TITLE
9****orn点击视频，视频播放不了

### ISSUE THREAD

**Issue by zwlj** [techGay/v9porn#223]
点击视频，然后跳视频解析中，后面就直接跳转首页了。
1.19版本

**Comment by techGay** [comment]
应该是触发了google的人机验证，导致获取不到数据app崩溃了

**Comment by zwlj** [comment]
> 应该是触发了google的人机验证，导致获取不到数据app崩溃了

那怎么解决呢，我点手动人机验证没什么作用，会跳出以下的页面![IMG_20201222_120512.jpg](https://user-images.githubusercontent.com/30178623/102847706-f5af2980-444d-11eb-9763-1bdf19282f58.jpg)

**Comment by techGay** [comment]
> > 应该是触发了google的人机验证，导致获取不到数据app崩溃了
> 
> 那怎么解决呢，我点手动人机验证没什么作用，会跳出以下的页面![IMG_20201222_120512.jpg](https://user-images.githubusercontent.com/30178623/102847706-f5af2980-444d-11eb-9763-1bdf19282f58.jpg)

晚点我看看

**Comment by zwlj** [comment]
这个问题好解决吗？

**Comment by techGay** [comment]
因为我本地和手机测试都是正常的，比较难复现出来
