### ISSUE TITLE
MIUI12   安卓10 闪退

### ISSUE THREAD

**Issue by 395741000** [techGay/v9porn#226]
![Screenshot_2020-12-27-13-41-41-841_com miui bugreport](https://user-images.githubusercontent.com/38332923/103164701-8d938580-4849-11eb-9a01-92f764ec896f.jpg)

**Comment by a935123246** [comment]
这个版本已经不能用了，https://t.me/v9Porn群组里下载humanfavorite123.apk，改成官网链接地址使用。
