### ISSUE TITLE
大佬 能给个最新的吗 我下的是1.01的 我不会玩编译 感谢大佬了

### ISSUE THREAD

**Issue by jueerye** [techGay/v9porn#26]
### 运行环境 ###

- [x] 手机型号：如：`魅族PRO 6`
- [x] 系统版本：如 `Android 7.1`
- [x] APP 版本：`1.0.1`

我下载了1.0.1的 在这里大佬你不更新了 我自己不会玩编译  请求大佬能更新下最新的版本 万分感谢

**Comment by molixiaoge** [comment]
apk目录下不是放着了，傻不傻
