### ISSUE TITLE
最新版账号无法登录

### ISSUE THREAD

**Issue by xudamian** [techGay/v9porn#27]
![screenshot_2018-05-18-07-39-07-905_com u9porn](https://user-images.githubusercontent.com/36026785/40208902-cc465292-5a6e-11e8-8afb-68988a85d13b.png)
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by zzzop** [comment]
你地址对了吗，浏览器能登录吗

**Comment by xudamian** [comment]
地址浏览器是可以登录的，，首页视频可以看，但无法登录帐号

**Comment by techGay** [comment]
因为服务器帮你跳转了，所以你还可以正常观看视频，但是无法登录，新版已经加入这个跳转机制了
