### ISSUE TITLE
登录账号视频看不了报错，不登录账号就可以看

### ISSUE THREAD

**Issue by bobcatss** [techGay/v9porn#31]
### 运行环境 ###

- [x] 手机型号：如：`小米6`
- [x] 系统版本：如 `Android 7.0`
- [x] APP 版本：`1.0.5`

界面截图
http://wx2.sinaimg.cn/mw690/0060lm7Tly1frpv2q7jrvj30u01g3gmy.jpg

不登录账号就可以看，网站是不是对账号进行了限制。
收藏问题，楼下帖子已经发过了，什么时候修复？

**Comment by techGay** [comment]
app 版本1.0.5？？？
1. 我本地测试登录账号观看没有问题
2. 至于收藏问题，其实只是提示收藏过了，但是其实已经是收藏成功了的，可以去我的收藏看看就知道了

**Comment by trychoozee** [comment]
地址填什么才可以登陆，我的是一直没办法登陆
