### ISSUE TITLE
登录帐号后可能被限制次数报错，不登陆可以无限看

### ISSUE THREAD

**Issue by mjuiujmnuj** [techGay/v9porn#32]
### 运行环境 ###

- [x] 手机型号：如：`一加5`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.0.2`

###报错字符 nullpointerexpetion###

**Comment by techGay** [comment]
报nullpointerexpetion是解析数据出错了，不是观看次数受到限制，如果是观看次数限制会直接提示的；
但是这个nullpointerexpetion是已经捕抓了，但当前版本并不将它上传后台，我没办法看到日志，无法定位问题
如果你自己可以下载源码运行看看logcat的日志具体的报错信息定位到什么问题
不然只能我下版本增加这个报错上传后台了

**Comment by trychoozee** [comment]
哪位大神可以分享一下地址怎么填写，才能登陆
