### ISSUE TITLE
朱古力网页加验证了

### ISSUE THREAD

**Issue by cilone** [techGay/v9porn#38]
貌似朱古力网页加google机器人验证了，app里打开提示403错误。

**Comment by techGay** [comment]
没问题的，你自己的网络或者梯子问题

**Comment by cilone** [comment]
可能我没表达清楚，我的梯子可以在网页打开，不过最近网页打开朱古力先有个Google的机器人验证，然后才能进去。V9客户端就是显示http403了。

**Comment by wzftesla** [comment]
可以分享一下朱古力网址吗😊

**Comment by techGay** [comment]
那这个好像没办法，感觉应该还是你那边的网络环境引起的，激发了这个机器人验证，我这边网页打开正常，没有验证（不过我很少用）
