### ISSUE TITLE
Mix2S 屏幕下方有白条

### ISSUE THREAD

**Issue by zkfpk6** [techGay/v9porn#39]
### 运行环境 ###

- [x] 手机型号：XiaoMi MIX 2S
- [x] 系统版本：Android 8.0
- [x] APP 版本：1.0.3

### 具体问题描述(如何操作，有何提示文字等): ###
Mix2S 屏幕下方有白条

**Comment by techGay** [comment]
这个适配问题，之前好像锤子的也有，我手头上没有相关机子可以测试，看看后面怎么解决吧

**Comment by zkfpk6** [comment]
之前抽屉版本的91是好的，这个我感觉是bottom navigation的问题

**Comment by techGay** [comment]
应该不会，可能是滑动关闭的库引起的
