### ISSUE TITLE
图片保存后的扫描问题

### ISSUE THREAD

**Issue by SkyFlyTang** [techGay/v9porn#40]
图片保存后我觉得不要用 
       Intent intent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
        intent.setData(uri);
        sendBroadcast(intent)这种方式了
直接用MediaScannerConnection 上面那种方式 我小米4刷的Android 8 就不能显示在相册中

**Comment by techGay** [comment]
这个问题确实有，之前看了一篇文章专门说这个的，不过一直还没机会改

**Comment by SkyFlyTang** [comment]
还有一个问题 新版本的gradle不要用compile 编译不通过 可以用api来代替
