### ISSUE TITLE
unexpected end of stream，导致Filedownloder不断点续传，这个怎么规避

### ISSUE THREAD

**Issue by ykrank** [techGay/v9porn#43]
之前自己也写过，用的也是Filedownloder和Okhttp，发现服务器对于http的实现有点问题，每次断开时都是206错误，unexpected end of stream。然而Filedownloder对于这个错误所做的操作是直接重新下载，导致很有可能永远下不下来，我最终是通过重写Filedownloder对于这个错误也断点续传来解决的，这个项目对于这个问题是怎么解决的呢？

**Comment by techGay** [comment]
我这边并没有任何处理，只是简单的使用这个库而已；你可以去Filedownloder 提issues吧，不过这本身是服务器的问题，毕竟少数，应该比较难统一。

OKHTTP官方好像也没有好的办法：https://github.com/square/okhttp/issues/2738
