### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by setsunadoudou** [techGay/v9porn#45]
@techGay  大佬，发现一个bug(不确定是个人问题还是有其他人出现这种问题)
### 运行环境 ###

- [x] 手机型号：`OPPO r7s`
- [x] 系统版本： `Android 4.4.4`
- [x] APP 版本：`v1.0.4`

### 具体问题描述(如何操作，有何提示文字等): ###
登录之后，随便点击一个视频会报空指针异常NullPointerException
（另，在未登录时，点击视频播放正常，点击对应发布者用户，需要登录，登录之后，点击发布者，能够看到发布者的视频，但是随意点一个视频，同样也会报空指针）
#### 问题截图: ####
无
#### 自己尝试了哪些，结果如何? ####
退出登录点击视频，能够正常播放

**Comment by techGay** [comment]
应该是你自己的问题，换地址或者换账号试试，目前不确定是什么原因，只知道你登录之后就无法解析视频链接了

报错地方：：ParseV9PronVideo.java:212com.u9porn.parser.ParseV9PronVideo.parseVideoPlayUrl。

也许是你帐号被限制了，或者地址问题，换个免梯子的地址或者换个帐号试试吧，不然就是你自己手机的问题，我目前没办法复现。

**Comment by setsunadoudou** [comment]
@techGay  应该是自己问题，这几天又好了。
