### ISSUE TITLE
无法注册用户

### ISSUE THREAD

**Issue by hiqz** [techGay/v9porn#50]
安卓8.0
注册时提示错误，好像是google什么的(我google全家桶)，闪的太快没看清。尝试重新注册提示邮件地址已经存在。
尝试登陆，提示无效用户名或密码太简单？我的密码12位，字母＋数字组合。
这个到底该如何注册呢？

**Comment by techGay** [comment]
很简单呀，去官网注册就可以了啊，然后再来登录就可以了，注册这个功能不稳定，很多接口随时都可能变动，我不可能每次发布都把功能都测一遍的

**Comment by zzzop** [comment]
你先去试试吧

**Comment by tongsuo** [comment]
在v9porn 客户端上试？

zzzop <notifications@github.com> 于 2018年8月31日 周五 08:26写道：
