### ISSUE TITLE
视频地址解析失败

### ISSUE THREAD

**Issue by lisw7** [techGay/v9porn#53]
### 运行环境 ###

- [x] 手机型号：如：`小米 8 `
- [x] 系统版本：如 `Android 8.1`
- [x] APP 版本：`1.0.6`

### 具体问题描述(如何操作，有何提示文字等): ###
A*gle地址设置成功，也可以正常打开页面，但打开任一视频均提示视频地址解析失败

#### 问题截图: ####
![image](https://user-images.githubusercontent.com/14174284/44887407-bc8fa000-acfe-11e8-95cf-d6a27e08bdff.png)

#### 自己尝试了哪些，结果如何? ####
地址设置的应该是没有问题吧？地址测试是成功的

**Comment by techGay** [comment]
我本地测试没问题，现在还不好判断什么原因，大概率应该还是和网络环境有关系

**Comment by tongsuo** [comment]
这个怎么注册不了

**Comment by lisw7** [comment]
@techGay 问题已解决，设置地址时最后加了“/”解决的，感谢大大，另外请问请你喝咖啡的二维码是哪个平台，用什么软件扫码······？
