### ISSUE TITLE
验证码始终刷不出来

### ISSUE THREAD

**Issue by djxxjd** [techGay/v9porn#56]
### 运行环境 ###

- [x] 手机型号：Oneplus6
- [x] 系统版本：Android 8.1
- [x] APP 版本：1.0.6

#### 自己尝试了哪些，结果如何? ####
换卡  换vps  还是刷不出来

**Comment by techGay** [comment]
没问题的，你自己的网络问题或者地址问题，不行卸载重新安装试试

验证码其实要不要无所谓，服务器不会验证的

**Comment by djxxjd** [comment]
好的  没什么必要  我就不登录了   再问下  a*gle的api地址加载不出来视频   有解决方案吗

**Comment by techGay** [comment]
因为视频地址是根据你填写的地址进行替换解析的，如果你的地址正确（别忘了最后的“/”），那么一般情况都能解析到，不然就是你梯子的问题，因为我测试也有部分梯子没办法解析。
