### ISSUE TITLE
朱古力有预览图，视频一直缓冲

### ISSUE THREAD

**Issue by lj98lj98** [techGay/v9porn#58]
### 运行环境 ###

- [x] 手机型号：如：`Huawei P10p`
- [x] 系统版本：如 `Android 8.0`
- [x] APP 版本：`1.0.6`

**Comment by lj98lj98** [comment]
以前没问题，今天试过多次都一样。

**Comment by techGay** [comment]
晚点我看看吧，可能接口有变动了

**Comment by techGay** [comment]
视频地址API变了，下个版本修复

**Comment by lj98lj98** [comment]
每天过来看看

**Comment by Mehamedahshan** [comment]
朱古力视频 添加设置成功
91视频可以正常观看，朱古力视频则不行
我的也是这样的现象，有预览图，但一直缓冲中，
手机型号huowei mate8
Android系统  7.0
APP版本 1.0.6

**Comment by lj98lj98** [comment]
国庆节有福利吗？
