### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by yz19870** [techGay/v9porn#59]
### 运行环境 ###

- [x] 手机型号：如：`VIVO  X21`
- [x] 系统版本：如 `Android 8.1.0
- [x] APP 版本：`所有

### 具体问题描述(如何操作，有何提示文字等): ###
安装不成功，每个版本都试过了，没有提示，就是显示安装失败

**Comment by techGay** [comment]
https://zhidao.baidu.com/question/924847951161887419.html
开启运行安装未知来源应用试试

或者你如果可以下载源码自己改配置试试，不然只能等我下个版本改了
https://blog.csdn.net/wufeng55/article/details/80659260
