### ISSUE TITLE
折腾一上午apk终于打包成功了

### ISSUE THREAD

**Issue by chengdr** [techGay/v9porn#6]
### 运行环境 ###

- [x] 手机型号：如：坚果pro
- [x] 系统版本：如 `Android 7.1.1`
- [x] APP 版本：最新

1.论坛里面图片无法加载
2.视频没法下载，有的可以下载有的会下载失败。。
3.

**Comment by xudamian** [comment]
能告诉一下 是用什么编译的吗?

**Comment by ceculean** [comment]
下载地址多少，确实不会编译啊，谢谢了。

**Comment by xudamian** [comment]
不会 就用老版的     不会就去找别人编译
