### ISSUE TITLE
9*视频加载一直转圈圈

### ISSUE THREAD

**Issue by diyici18sui** [techGay/v9porn#60]
### 运行环境 ###

- [x] 手机型号：ZUK Z2
- [x] 系统版本：Android 7.1.2
- [x] APP 版本：1.0.6

地址设置完成后，9*视频加载一直转圈圈。尝试过翻*地址+不可描述，无限转圈；免翻*地址，无限转圈，同时朱古力和a*gle 没有问题。pc端用不可描述没问题。。请问是怎么回事儿···

**Comment by techGay** [comment]
如果你确认地址肯定正确的话，我目前推测不出什么原因，可以的话你下载源码看看输出日志才懂

**Comment by diyici18sui** [comment]
@techGay 感谢回复，小白，不太懂那些，抱歉无法完成后续

**Comment by Mehamedahshan** [comment]
avgle的api地址哪位大神发一下

**Comment by diyici18sui** [comment]
@Mehamedahshan api.a*gle.com

**Comment by seeysa** [comment]
> @Mehamedahshan api.a*gle.com

http://api.avgel.com/  这个无法测试通过
