### ISSUE TITLE
可以在线看不能下载

### ISSUE THREAD

**Issue by ioojcn** [techGay/v9porn#63]
### 运行环境 ###

- [x] 手机型号：如：三星S7E
- [x] 系统版本：如 `Android 8.0`
- [x] APP 版本：`1.0.6`

### 具体问题描述(如何操作，有何提示文字等): ###
可以在线看.不能下载.下载页面显示 下载错误.挂SS也不能下载...是不是什么API之类的更新了额?

**Comment by ioojcn** [comment]
可以下载了。发现了新问题。

除了主页能看以外，其他标签下的视频点击后app自动关闭。


问下朱古力和a*gle是什么网站

**Comment by techGay** [comment]
修复了
