### ISSUE TITLE
建议修改默认下载文件夹路径

### ISSUE THREAD

**Issue by sakuyamaij** [techGay/v9porn#65]
当前默认路径还是sd卡的根目录，用来存放小视频实在有些不太妥。
希望能够默认路径/storage/emulated/0/Movies
配合第三方软件储存重定向，可以在sd卡根目录彻底消灭掉.DataStorage和.UTSystemConfig这2个隐藏文件夹。
产品本身没遇到什么问题，就是觉得这个默认路径不太符合规范，所以提个建议。

**Comment by techGay** [comment]
1. 默认路径并不是根目录，是在v9porn文件夹下
2.常规的应用程序可以这样做，但是我相信大多数人肯定不会想要这样，因为多数人下载了视频之后更想的是怎么方便观看和隐藏，放到公有目录更容易被其他软件或者系统扫描到，如果别人借手机一不小心....

**Comment by sakuyamaij** [comment]
谢谢解答，清空app试了下，是我自己的原因误改了自定义下载路径，导致产生了误会。不好意思
