### ISSUE TITLE
无法登陆9 * 1提示NullPointerException错误

### ISSUE THREAD

**Issue by make9** [techGay/v9porn#66]
### 运行环境 ###

- [x] 手机型号：如：`华为8`
- [x] 系统版本：如 `Android 8.0`
- [x] APP 版本：`1.08`

无法登陆9*1 提示NullPointerException错误
用不用梯子都一样错误

**Comment by techGay** [comment]
我本地测试没有发现问题，估计可能和你账号缺乏一些或者多了一些信息有关，你可以试试在电脑上能不能。
如果可以下载源码编译看看报错的日志

**Comment by make9** [comment]
经过测试 是9*1账号本身问题。一般几年前的老帐号出现这个问题

**Comment by seeysa** [comment]
> 经过测试 是9*1账号本身问题。一般几年前的老帐号出现这个问题

刚才新注册了个账号  依旧不能登陆 pc网页可登
