### ISSUE TITLE
客户端下载视频经常出现问题。动不动就是出现错误，然后已经下了大半的视频又会从头开始下载

### ISSUE THREAD

**Issue by Astem94** [techGay/v9porn#67]
### 运行环境 ###

- [x] 手机型号：一加3
- [x] 系统版本：Android 8.0
- [x] APP 版本：1.0.8

**Comment by techGay** [comment]
1.下载错误原因很多，可能跟你自身的网络有关，也可能是服务器的问题
2.下载大半的视频重新下载是怎么操作的，当前版本存在还是一直存在？
