### ISSUE TITLE
编译的时候提示模块'v9porn-master'不支持gradle

### ISSUE THREAD

**Issue by xudamian** [techGay/v9porn#7]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

### 具体问题描述(如何操作，有何提示文字等): ###
无法编译，提示模块'v9porn-master'不支持gradle

**Comment by chengdr** [comment]
是你笨

**Comment by xudamian** [comment]
@chengdr你他妈傻逼，问你了吗？
