### ISSUE TITLE
zhuguli带有谷歌机器人验证，无法正常访问

### ISSUE THREAD

**Issue by pk250** [techGay/v9porn#72]
输入zhuguli网址之后出现403错误，直接网页访问发现有谷歌的机器人验证

**Comment by techGay** [comment]
这个暂时没办法，因为跟你使用的梯子环境有关，触发了Google的人机验证，这个绕不过去的

**Comment by Golidy** [comment]
能不能有个大神解答下什么是zhuguli网站，给一点点发布页提示也行，跪谢

**Comment by anleihn** [comment]
谷歌搜索zhuguli你就知道了

**Comment by Golidy** [comment]
> 谷歌搜索zhuguli你就知道了

我用了谷歌百度，结果前五条分别是youtube视频，词典翻译，推特地址，vimeo，然后又是youtube，我还可以关了安全搜索。

**Comment by Golidy** [comment]
> > 谷歌搜索zhuguli你就知道了
> 
> 我用了谷歌百度，结果前五条分别是youtube视频，词典翻译，推特地址，vimeo，然后又是youtube，我还可以关了安全搜索。

神了，我打开安全搜索就出来了，谢谢

**Comment by Golidy** [comment]
thanks

**Comment by Golidy** [comment]
> 谷歌搜索zhuguli你就知道了

请问下，a*gle为什么只有缩略图无法播放呢？我开了FQ软件，其他zhuguli和9*都可以正常使用。

**Comment by w1997415** [comment]
> 输入zhuguli网址之后出现403错误，直接网页访问发现有谷歌的机器人验证

分享下网址？？？
