### ISSUE TITLE
引起系统界面崩溃

### ISSUE THREAD

**Issue by tripleHsingleP** [techGay/v9porn#73]
### 运行环境 ###

- [x] 手机型号：如：`oneplus 5`
- [x] 系统版本：如 `Android 8.0.0`
- [x] APP 版本：`1.0.0`

### 具体问题描述(如何操作，有何提示文字等): ###
使用app看视频没问题，点击下载后system ui会一直重启。
#### 自己尝试了哪些，结果如何? ####
使用1.0.0版本的apk没有该问题，其他版本都有。手机装了xposed，但是关闭框架后问题没有解决。

**Comment by techGay** [comment]
这样描述看不出什么问题，点击下载就会启动服务，然后显示通知开始下载；如果是权限问题，怎么也是App自己崩溃，不会造成系统的system ui 崩溃，唯一点可能就是通知那里，但是也无法判定什么问题，后台也没有上传任何的关于这个的崩溃日志
