### ISSUE TITLE
http代理能不能加上一个用户名和密码？

### ISSUE THREAD

**Issue by lukemin** [techGay/v9porn#76]
http代理能不能加上一个用户名和密码？ 我有自己的服务器但是怕被盗用。

**Comment by techGay** [comment]
Http代理只是代理网页的加载而已，加是可以加，但是意义不是很大，回头我看看再加吧

**Comment by lukemin** [comment]
看视频不是也通过代理加载吗？zhuguli和av*gle需要代理才能访问，正好不想全局代理

**Comment by techGay** [comment]
1. HTTP代理只代理网页，视频播放走的是系统网络，系统网络是什么就是什么，目前是这样
2.不想全局代理很简单，使用免梯子地址，然后梯子里设置仅代理中国大陆无法访问的地址就ok了

**Comment by lukemin** [comment]
那样子的话，代理基本没用啊，要是能全局代理好了，ssr太费电了！

**Comment by lukemin** [comment]
如果能内置代理就好了，和telegram一样挺方便的

**Comment by lukemin** [comment]
我telegram的节点也是自己的服务器建立啊。现在服务器很便宜，但是我不想一直开着ssr，太费电了。

**Comment by techGay** [comment]
内置还不是一样的，要使用ssr，那就是把那套移植过来而已，该跑的该耗电的一样

**Comment by lukemin** [comment]
我说的不是ssr，而是socks5的代理，像tg一样。

**Comment by techGay** [comment]
视频走socks5，没试过，回头看看

**Comment by qgtxqj** [comment]
完全没必要，ssr不用基本不耗电。不想用ssr还有drony可以解决各种各样的代理。
