### ISSUE TITLE
点击登录后提示登录中然后消失，依然停留在登录页面

### ISSUE THREAD

**Issue by hmxxhmzx** [techGay/v9porn#77]
### 运行环境 ###

- [x] 手机型号：Xiaomi Mix2s
- [x] 系统版本：Android 9.0 MIUI 10.0.7.0
- [x] APP 版本：1.0.8

### 具体问题描述(如何操作，有何提示文字等): ###
登录账号提示 “登录中，请稍后。。。”进度条滚动两圈后消失，还是停留在登录页面，不会返回退出，不会报错，也没有成功登录。确认账户密码验证码无误，已用SS翻墙，视频观看下载无问题。

#### 自己尝试了哪些，结果如何? ####
原本是1.0.5版本，以为是版本问题，更新为1.0.8之后问题依旧
补充：测试了一下，不管填写什么内容，用户名密码验证码全部乱填，一样的结果，不会提示错误，但也没有任何反应。

**Comment by techGay** [comment]
我本地自己账号测试没有问题（注册测试用的，比较新），之前也有人反应老账号登陆有问题，但是我也不知道什么问题，因为看不到相关的信息，无法确定

**Comment by peipei1024** [comment]
注册的是9.1  porn的账号吗？

**Comment by techGay** [comment]
注册去官网吧，下版本关闭这个功能了，只维护登录功能了

**Comment by peipei1024** [comment]
能登录进去吗

**Comment by meablelee2013** [comment]
登录之后返回值是空字符串，里面并没有username,userId等信息，而在cookie里好像加了一些东西

**Comment by meablelee2013** [comment]
可能需要兼容返回值为""的情况，登录成功之后的接口都会在cookie里带上登录下发的cookie,
