### ISSUE TITLE
账号登录提示NullPointerException错误

### ISSUE THREAD

**Issue by xiechangan123** [techGay/v9porn#83]
### 运行环境 ###

- [x] 手机型号：如：`小米5s plus`
- [x] 系统版本：如 `Android 8.0`
- [x] APP 版本：`1.0.8`

### 具体问题描述(如何操作，有何提示文字等): ###
账号登录提示NullPointerException错误，确定账号密码都是正确的
#### 自己尝试了哪些，结果如何? ####
在pc网页登录是可以，就是软件不行。看反馈，有人跟我情况一样。我的账号也是老帐号了，这个问题无法解决么？

**Comment by techGay** [comment]
可以解决，但是我没有老账号测试，只能最简单解析信息的时候多加几个判断，但是可能会导致信息显示不全

**Comment by xiechangan123** [comment]
这样吧，我把账号密码发你邮箱，你自己测试下，修复了也是造福大家啊

**Comment by wsqzwa** [comment]
只要有老账号就可以测试bug了吗？

**Comment by techGay** [comment]
只要有帐号，我本地复现，看到日志就可以了

**Comment by seeysa** [comment]
特意新注册了一个账号 也不能登陆

**Comment by seeysa** [comment]
> 只要有帐号，我本地复现，看到日志就可以了

特意新注册了一个账号 也不能登陆

**Comment by seeysa** [comment]
> 可以解决，但是我没有老账号测试，只能最简单解析信息的时候多加几个判断，但是可能会导致信息显示不全

特意新注册了一个账号 也不能登陆  新老账号都不能登陆了

**Comment by Yoshino-s** [comment]
so, how to solve it?

**Comment by techGay** [comment]
下版本修复，静待i
