### ISSUE TITLE
请问你在爬取网页数据的时候，有遇到中文字符是乱码的情况吗

### ISSUE THREAD

**Issue by ElvistLui** [techGay/v9porn#86]

**Comment by techGay** [comment]
没有，一般设置你的请求头为："Accept-Language", "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5"就不会有问题

**Comment by ElvistLui** [comment]
我的请求Header设置参照你的安卓端，包括"Accept-Language"但还是中文乱码。
我用了个奇葩的办法解决了。先用iOS系统的WKWebView加载网页，等加载完成后在再通过js获取WKWebView上的html代码就正常了。。。

**Comment by techGay** [comment]
你这样会很慢吧，除非你能控制WKWebView不加载图片和JS脚本，或者WKWebView加载完基本的html后
就回调给你才去执行JS脚本和加载图片。

你可以看看返回的请求头的编码是什么，根据编码去解析应该就不会乱码了（一般来说现在基本都是Content-Type: text/html; charset=utf-8，不用特殊处理）

**Comment by ElvistLui** [comment]
用WKWebView加载目前是很慢。
Response的Header里确实是text/html; charset=utf-8，我在Request里做了各种参数尝试，结果都一样。

**Comment by techGay** [comment]
那应该和服务器没什么太大关系了，应该是你本地请求到数据后转换成字符串时编码不正确吧，你可以自己尝试拿到最初的流byte[]然后指定不同的编码转成字符串看看，如果还不行那我也不清楚了

**Comment by ElvistLui** [comment]
嗯呢好的，多谢
