### ISSUE TITLE
a*gle视频内容与标题不符

### ISSUE THREAD

**Issue by lisw7** [techGay/v9porn#87]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by techGay** [comment]
这个并不是软件本身问题，是服务器问题，你网页看的时候有时候也会这样，也许是上传的人故意搞的标题吸引流量而已

**Comment by lisw7** [comment]
并不是一两个视频哈，是所有视频均是····我追溯了项目JAViewer，那边也是集中反馈这个问题···是不是咱用了那边一样的所以也是这问题，大大可以尝试下

**Comment by TGhoul** [comment]
作者说的对，这个是 API 原因，只能等 API 修复了

**Comment by lisw7** [comment]
这个API还没有修复吗？······
