### ISSUE TITLE
当前版本v1.0.9已知问题以及反馈

### ISSUE THREAD

**Issue by techGay** [techGay/v9porn#88]
问题1：9*porn无法登录的，请卸载重装

**Comment by cilone** [comment]
新版会有观看次数达到上限提示，让换地址或代理服务器。

**Comment by cilone** [comment]
新版还发现个问题，A*gle视频播放不了，网页里可以播放，不知道是不是个别问题。

**Comment by techGay** [comment]
> 新版还发现个问题，A*gle视频播放不了，网页里可以播放，不知道是不是个别问题。

只要你地址设对了，一般都能播放，如果不能，多数跟你梯子的网络环境有关（当前版本我本地测试没问题）

**Comment by xiechangan123** [comment]
1.09版本不登陆的情况下，只能看作者所有作品中排名前5-6个视频左右，更多的视频就一直处于刷新状态无法加载。如果是登录的情况下，可以看作者所有视频，不存在刷新问题，但是会有数量限制，搞到最后就跟游客一样，只能看几个视频就提示观看次数达到上限。
求解决

**Comment by mrpoull** [comment]
在哪下载？

**Comment by techGay** [comment]
> 1.09版本不登陆的情况下，只能看作者所有作品中排名前5-6个视频左右，更多的视频就一直处于刷新状态无法加载。如果是登录的情况下，可以看作者所有视频，不存在刷新问题，但是会有数量限制，搞到最后就跟游客一样，只能看几个视频就提示观看次数达到上限。
> 求解决

1. 确实不登录只能加载作者前几个视频 
2. 我这边测试不登录的情况下，没有观看次数的限制
3. 登录的情况我没有测，如果登录之后有观看限制，目前不知道服务器是不是基于帐号做了次数限制，如果是，那就没办法了

**Comment by xiechangan123** [comment]
针对第二点，关键是很多作者的视频很不错，要是不登录的话，是无法观看的。第三点估计没人愿意假设服务器吧。这些问题，能解决就解决，不能解决大不了不看了。其实也没多大事

**Comment by suojiang** [comment]
P*gav 访问不了，另外三个地址ok没问题
![screenshot_20190116-121833_v9porn](https://user-images.githubusercontent.com/12185015/51226180-32806500-1989-11e9-88bb-810e0fcea2f4.jpg)

**Comment by techGay** [comment]
> P*gav 访问不了，另外三个地址ok没问题
> 图片包含敏感信息，屏蔽了

你这个看起来是证书错误问题，网页访问显示是有效的证书，感觉跟你的梯子有关，应该跟app没多大关系

**Comment by zbb1213440217** [comment]
更新了新版本，根本下载不了视频啊，原来下载的地方现在按不了，我想知道现在怎么下载啊？

**Comment by zbb1213440217** [comment]
下载视频很重要啊，现在这个功能却不好用了

**Comment by techGay** [comment]
> 更新了新版本，根本下载不了视频啊，原来下载的地方现在按不了，我想知道现在怎么下载啊？

1. 你之前用的那个版本？因为这个版本没有对下载那块进行任何改动

**Comment by zbb1213440217** [comment]
> > 更新了新版本，根本下载不了视频啊，原来下载的地方现在按不了，我想知道现在怎么下载啊？
> 
> 1. 你之前用的那个版本？因为这个版本没有对下载那块进行任何改动

我用的是1.0.0之前的版本，版本号记不清楚了，因为下了很多视频，所以没用最新的，今天把视频挨个改了名字，现在就有两点不足，第一个就是下载不了，第二个就是我在1.0.0之前那个版本下载的视频就是全是机器码，并不是我下载下来的文件名，导致我得一个一个改名字
![screenshot_2019-01-18-20-19-10-07](https://user-images.githubusercontent.com/45889027/51386704-51aefc00-1b1b-11e9-986e-b5cc293fb86e.png)

**Comment by zbb1213440217** [comment]
> > > 更新了新版本，根本下载不了视频啊，原来下载的地方现在按不了，我想知道现在怎么下载啊？
> > 
> > 
> > 
> > 1. 你之前用的那个版本？因为这个版本没有对下载那块进行任何改动
> 
> 我用的是1.0.0之前的版本，版本号记不清楚了，因为下了很多视频，所以没用最新的，今天把视频挨个改了名字，现在就有两点不足，第一个就是下载不了，第二个就是我在1.0.0之前那个版本下载的视频就是全是机器码，并不是我下载下来的文件名，导致我得一个一个改名字
> ![screenshot_2019-01-18-20-19-10-07](https://user-images.githubusercontent.com/45889027/51386704-51aefc00-1b1b-11e9-986e-b5cc293fb86e.png)



> > 更新了新版本，根本下载不了视频啊，原来下载的地方现在按不了，我想知道现在怎么下载啊？
> 
> 1. 你之前用的那个版本？因为这个版本没有对下载那块进行任何改动

第二个问题因为我下载不了，也不知道你改没改动

**Comment by techGay** [comment]
> > > 更新了新版本，根本下载不了视频啊，原来下载的地方现在按不了，我想知道现在怎么下载啊？
> > 
> > 
> > 
> > 1. 你之前用的那个版本？因为这个版本没有对下载那块进行任何改动
> 
> 我之前用的是1.0.0之前的版本，将近一年之前的版本了，很早，今天才把视频导出来改改视频名字，但是那个可以下载，这个下载不了，我也不知道为什么就是下载不了。现在就是有两个问题，第一个就是下载不了，第二个就是我下载之后全都是机器码，根本不是下载时候的文件名，第二个问题我现在下载不了我也不知道改没改，给你看截图，就类似于这种，我想导出来还得改名字
> ![img_20190118_202817](https://user-images.githubusercontent.com/45889027/51387051-95eecc00-1b1c-11e9-9b99-edb8afb3a892.jpg)

1. 下载一个都下不了，不太可能的，只要你挂了梯子，绝大多数都能下（有一种可能就是解析的时间久了链接失效了可能就不能下载了，后续可以考虑增加个重新获取最新地址）
2.当前1.0.9版本已经不是机器码了，因为当初考虑到标题可能会有一些特殊的字符无法保存为文件名，所以才用的机器码

**Comment by zbb1213440217** [comment]
还是下载不了，我用的SS应该没问题的，最早那个版本就可以，试了08那个版本，也下载不了，不知道为什么，这个加号就是点不了，我手机也重启了，也重装了软件，不太懂
![img_20190119_095931](https://user-images.githubusercontent.com/45889027/51420841-3cbf8080-1b8e-11e9-9bab-c554402f344f.jpg)

**Comment by zbb1213440217** [comment]
但是这个加号在主页面可以点，就是到了下载页面不能点😂.无论怎么点都点不了

**Comment by make9** [comment]
这个版本源码好像无法编译？
D:\apkpj\v9porn-master\config.gradle (系统找不到指定的文件。)
Open File

**Comment by techGay** [comment]
> 这个版本源码好像无法编译？
> D:\apkpj\v9porn-master\config.gradle (系统找不到指定的文件。)
> Open File

这个只是一些私有的配置信息，你可以自己新建这个文件，把缺失的appkey和appId写上去就可，或者你可以直接去掉bugly的依赖也可以

**Comment by yjandroid** [comment]
还是没办法编译始终提示这个
ERROR: Failed to resolve: support-media-compat
Affected Modules: exolibrary

**Comment by wsqzwa** [comment]
> > 新版还发现个问题，A*gle视频播放不了，网页里可以播放，不知道是不是个别问题。
> 
> 只要你地址设对了，一般都能播放，如果不能，多数跟你梯子的网络环境有关（当前版本我本地测试没问题）

我的地址明明是对的啊  谷歌一搜第一个就是啊  而且同样的网址我放在电脑上或者手机浏览器上都可以正常登陆啊但是一把它设为APP里面的avgle地址时候就是HTTP 404  这是为什么 难道还需要每次用的时候我再设置一下HTTP代理设置嘛~
