### ISSUE TITLE
第三方库用的太多，有没有计划梳理精简下

### ISSUE THREAD

**Issue by xlxl2010** [techGay/v9porn#9]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by chengdr** [comment]
那你开发一个。

**Comment by techGay** [comment]
你指的哪些？像Rxjava2，dagger2，retrofit，还有数据库框架这些基本的东西肯定不能的，其他的有些也只是调试用而已，或者你可以精简了提交PR
