### ISSUE TITLE
不好意思，我是小白，有朋友给一下设置里面的地址吗？

### ISSUE THREAD

**Issue by qmhn2000** [techGay/v9porn#90]
地址没有，求地址，qmhn2000@163.com,谢谢

**Comment by qmhn2000** [comment]
没有大佬理我啊

**Comment by AnonymousH** [comment]
91视频地址  http://91porn.com/
91论坛地址 https://91dizhi-at-gmail-com-0201.p17.rocks/
P*av地址 https://pigav.com/
A*av地址 https://api.avgle.com/

**Comment by onloner2012** [comment]
hhhh,看傻了？:grinning::grinning:

**Comment by QuillerF** [comment]
> 91视频地址 ------------
> 91论坛地址-------------
> P_av地址 ----------------- A_av地址 --------------------
> 请私聊，不要在这贴地址信息

给我下地址吧,大佬

**Comment by qmhn2000** [comment]
91视频地址 http://91porn.com/
91论坛地址 https://91dizhi-at-gmail-com-0201.p17.rocks/
Pav地址 https://pigav.com/
Aav地址 https://api.avgle.com/

在 2019-03-11 17:13:07，"QuillerF" <notifications@github.com> 写道：


91视频地址 ------------
91论坛地址-------------
P_av地址 ----------------- A_av地址 --------------------
请私聊，不要在这贴地址信息

给我下地址吧,大佬

**Comment by fanzhenchen** [comment]
我的设置细地址有缩览图但是解析失败

**Comment by chenmuduo1997** [comment]
> 没有大佬理我啊

兄弟，弄上地址了吗？

**Comment by fanzhenchen** [comment]
我也是之前用的好好的虽然不维护维护了但是还能用，前段时间刷机了帮忘了截下图看下我之前怎么设置的了，然后我现在也用不了了












下周回国贾跃亭
1848382118@qq.com


---原始邮件---
发件人: "chenmuduo1997"<notifications@github.com&gt;
发送时间: 2019年12月13日(周五) 下午3:47
收件人: "techGay/v9porn"<v9porn@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"fanzhenchen"<1848382118@qq.com&gt;;
主题: Re: [techGay/v9porn] 不好意思，我是小白，有朋友给一下设置里面的地址吗？ (#90)


 
没有大佬理我啊
  
兄弟，弄上地址了吗？
