### ISSUE TITLE
Program type already present: io.victoralbertos.jolyglot.GsonSpeaker

### ISSUE THREAD

**Issue by seastar888** [techGay/v9porn#94]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

### 具体问题描述(如何操作，有何提示文字等): ###

AS里运行提示：
Program type already present: io.victoralbertos.jolyglot.GsonSpeaker
无法运行？请教...谢谢！

**Comment by techGay** [comment]
初步看是rxcache的问题，但是你贴的出错日志太少了，看不出具体的错误，把完整的出错栈信息贴上来

--还有不要随便该依赖库版本，特别是有相关联的时候

**Comment by seastar888** [comment]
Executing tasks: [:app:assembleDebug]

:app:buildInfoDebugLoader
:app:checkDebugClasspath UP-TO-DATE
:app:preBuild UP-TO-DATE
:exolibrary:preBuild UP-TO-DATE
:exolibrary:preDebugBuild UP-TO-DATE
:exolibrary:checkDebugManifest UP-TO-DATE
:exolibrary:processDebugManifest UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:exolibrary:compileDebugAidl NO-SOURCE
:app:compileDebugAidl NO-SOURCE
:exolibrary:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:greendaoPrepare UP-TO-DATE
:app:greendao
:app:prepareLintJar UP-TO-DATE
:app:mainApkListPersistenceDebug UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:exolibrary:compileDebugRenderscript UP-TO-DATE
:exolibrary:generateDebugResValues UP-TO-DATE
:exolibrary:generateDebugResources UP-TO-DATE
:exolibrary:packageDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:createDebugCompatibleScreenManifests UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:exolibrary:generateDebugRFile UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources
:exolibrary:generateDebugBuildConfig UP-TO-DATE
:exolibrary:prepareLintJar UP-TO-DATE
:exolibrary:generateDebugSources UP-TO-DATE
:exolibrary:javaPreCompileDebug UP-TO-DATE
:exolibrary:compileDebugJavaWithJavac UP-TO-DATE
:exolibrary:processDebugJavaRes NO-SOURCE
:exolibrary:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:javaPreCompileDebug UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:instantRunMainApkResourcesDebug UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:exolibrary:mergeDebugShaders UP-TO-DATE
:exolibrary:compileDebugShaders UP-TO-DATE
:exolibrary:generateDebugAssets UP-TO-DATE
:exolibrary:packageDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:validateSigningDebug UP-TO-DATE
:app:processInstantRunDebugResourcesApk UP-TO-DATE
:app:checkManifestChangesDebug
:app:transformClassesWithExtractJarsForDebug UP-TO-DATE
:app:transformClassesWithInstantRunVerifierForDebug UP-TO-DATE
:app:transformClassesWithDependencyCheckerForDebug UP-TO-DATE
:app:compileDebugNdk NO-SOURCE
:app:mergeDebugJniLibFolders UP-TO-DATE
:exolibrary:compileDebugNdk NO-SOURCE
:exolibrary:mergeDebugJniLibFolders UP-TO-DATE
:exolibrary:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
:exolibrary:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
:app:checkDebugLibraries UP-TO-DATE
:app:processDebugJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:transformNativeLibsAndResourcesWithJavaResourcesVerifierForDebug UP-TO-DATE
:app:transformClassesWithInstantRunForDebug UP-TO-DATE
:app:transformClassesAndClassesEnhancedWithInstantReloadDexForDebug UP-TO-DATE
:app:incrementalDebugTasks UP-TO-DATE
:app:preColdswapDebug
:app:fastDeployDebugExtractor UP-TO-DATE
:app:generateDebugInstantRunAppInfo UP-TO-DATE
:app:transformClassesWithDexBuilderForDebug UP-TO-DATE
AGPBI: {"kind":"error","text":"Program type already present: io.victoralbertos.jolyglot.GsonSpeaker","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
:app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\0.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\1.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\2.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\3.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\4.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\5.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\6.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\7.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\8.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\9.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\10.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\11.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\12.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\13.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\14.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\15.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\16.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\17.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\18.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\19.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\20.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\21.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\22.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\23.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\24.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\25.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\26.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\27.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\28.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\29.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\30.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\31.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\32.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\33.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\34.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\35.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\36.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\37.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\38.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\39.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\40.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\41.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\42.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\43.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\44.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\45.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\46.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\47.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\48.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\49.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\50.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\51.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\52.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\53.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\54.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\55.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\56.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\57.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\58.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\59.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\60.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\61.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\62.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\63.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\64.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\65.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\66.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\67.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\68.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\69.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\70.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\71.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\72.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\73.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\74.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\75.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\76.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\77.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\78.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\79.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\80.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\81.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\82.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\83.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\84.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\85.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\86.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\87.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\88.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\89.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\90.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\91.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\92.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\93.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\94.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\95.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\96.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\97.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\98.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\99.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\100.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\101.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\102.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\103.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\104.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\105.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\106.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\107.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\108.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\109.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\110.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\111.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\112.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\113.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\114.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\115.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\116.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\117.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\118.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\119.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\120.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\121.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\122.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\123.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\124.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\125.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\126.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\127.jar
  Program type already present: io.victoralbertos.jolyglot.GsonSpeaker
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
58 actionable tasks: 6 executed, 52 up-to-date

**Comment by seastar888** [comment]
Executing tasks: [clean, :app:assembleDebug, :exolibrary:assembleDebug]

:app:clean
:app:checkDebugClasspath
:app:preBuild UP-TO-DATE
:exolibrary:preBuild UP-TO-DATE
:exolibrary:preDebugBuild UP-TO-DATE
:exolibrary:checkDebugManifest UP-TO-DATE
:exolibrary:processDebugManifest UP-TO-DATE
:app:preDebugBuild
:exolibrary:compileDebugAidl NO-SOURCE
:app:compileDebugAidl NO-SOURCE
:exolibrary:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript
:app:checkDebugManifest
:app:generateDebugBuildConfig
:app:greendaoPrepare
:app:greendao
:app:prepareLintJar UP-TO-DATE
:app:mainApkListPersistenceDebug
:app:generateDebugResValues
:app:generateDebugResources
:exolibrary:compileDebugRenderscript UP-TO-DATE
:exolibrary:generateDebugResValues UP-TO-DATE
:exolibrary:generateDebugResources UP-TO-DATE
:exolibrary:packageDebugResources UP-TO-DATE
:app:mergeDebugResources
:app:createDebugCompatibleScreenManifests
:app:processDebugManifest
:app:splitsDiscoveryTaskDebug
:exolibrary:generateDebugRFile UP-TO-DATE
:app:processDebugResources
:app:generateDebugSources
:exolibrary:generateDebugBuildConfig UP-TO-DATE
:exolibrary:prepareLintJar UP-TO-DATE
:exolibrary:generateDebugSources UP-TO-DATE
:exolibrary:javaPreCompileDebug UP-TO-DATE
:exolibrary:compileDebugJavaWithJavac UP-TO-DATE
:exolibrary:processDebugJavaRes NO-SOURCE
:exolibrary:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:app:javaPreCompileDebug
注: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule]
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:app:compileDebugJavaWithJavac
:app:compileDebugNdk NO-SOURCE
:app:compileDebugSources
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:exolibrary:mergeDebugShaders UP-TO-DATE
:exolibrary:compileDebugShaders UP-TO-DATE
:exolibrary:generateDebugAssets UP-TO-DATE
:exolibrary:packageDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:transformClassesWithDexBuilderForDebug
:app:transformClassesWithMultidexlistForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 43s
37 actionable tasks: 22 executed, 15 up-to-date

**Comment by techGay** [comment]
这是引用了两个相同的库但是版本不一致导致编译时冲突，去掉其中一个即可    

检查你的app.gradle 确保下面这个库只引用当前的这最新版本
// To use Gson
    implementation 'com.github.VictorAlbertos.Jolyglot:gson:0.0.4'

**Comment by seastar888** [comment]
谢谢！已经重新编译成功。
原因是下载的代码中，版本是：
// To use Gson
implementation 'com.github.VictorAlbertos.Jolyglot:gson:0.0.3'

顺便请教一下，日志哪里看出来这个问题？

**Comment by techGay** [comment]
0.0.3 版本不知道什么时候失效了

F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\126.jar, F:\Andriod_projects\v9porn-master\app\build\intermediates\transforms\dexBuilder\debug\127.jar
Program type already present: io.victoralbertos.jolyglot.GsonSpeaker
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

最后官方给的链接已经说明了原因和解决办法了

**Comment by seastar888** [comment]
谢谢，当时有看到，但官方链接打不开，所以就不知道怎么解决了...

**Comment by seastar888** [comment]
谢谢，当时是有看到，但官方的链接打不开，又被提示误导了，所以就不知道怎么解决了...
